# Generated by Django 4.2 on 2023-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_account_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='images\\Vladimir_Putin_17-11-2021_(cropped).jpg', upload_to='images'),
        ),
    ]
